package me.pangrusak.verity;
import org.bukkit.*; import org.bukkit.command.*; import org.bukkit.entity.*; import org.bukkit.event.*; import org.bukkit.event.player.*; import org.bukkit.inventory.ItemStack; import org.bukkit.plugin.java.JavaPlugin; import org.bukkit.scheduler.BukkitTask; import java.util.*;
public final class VerityPresencePlugin extends JavaPlugin implements CommandExecutor,Listener{
 private ProfileStore store; private GroqClient groq; private final Random random=new Random(); private final Map<UUID,ArmorStand> active=new HashMap<>(); private BukkitTask events;
 @Override public void onEnable(){saveDefaultConfig();store=new ProfileStore(getDataFolder());groq=new GroqClient(this);Objects.requireNonNull(getCommand("verity")).setExecutor(this);getServer().getPluginManager().registerEvents(this,this);events=Bukkit.getScheduler().runTaskTimer(this,this::tick,100L,100L);String key=getConfig().getString("ai.api-key","").trim();if(key.isEmpty()||key.equals("PASTE_YOUR_GROQ_KEY_HERE"))getLogger().warning("Groq is not configured: edit plugins/VerityPresence/config.yml. API calls will use fallback lines.");}
 @Override public void onDisable(){if(events!=null)events.cancel();for(UUID id:new ArrayList<>(active.keySet()))remove(id);store.save();}
 @EventHandler public void join(PlayerJoinEvent e){PlayerProfile p=store.get(e.getPlayer().getUniqueId());if(p.accepted&&p.nextEventAt==0)schedule(p);}
 @EventHandler public void chat(AsyncPlayerChatEvent e){if(!getConfig().getBoolean("chat.listen-to-normal-chat",true))return;PlayerProfile p=store.get(e.getPlayer().getUniqueId());String m=e.getMessage();if(!p.accepted||ignored(m)||m.length()<getConfig().getInt("chat.minimum-message-length",4))return;boolean named=m.toLowerCase(Locale.ROOT).contains("verity");if(getConfig().getBoolean("privacy.require-name-for-normal-chat",false)&&!named)return;if(!named&&random.nextInt(100)>=getConfig().getInt("chat.response-chance-percent",12))return;Bukkit.getScheduler().runTask(this,()->groq.ask(e.getPlayer(),p,m));}
 @Override public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player)){s.sendMessage("Players only.");return true;}Player p=(Player)s;PlayerProfile x=store.get(p.getUniqueId());if(a.length==0){p.sendMessage(color("&e/verity accept, /verity leave, /verity status, or /verity <message>"));return true;}String sub=a[0].toLowerCase(Locale.ROOT);if(sub.equals("accept")){x.accepted=true;schedule(x);store.save();p.sendMessage(color(getConfig().getString("messages.accepted")));return true;}if(sub.equals("leave")){if(!x.accepted)p.sendMessage(color(getConfig().getString("messages.already-paused")));else{x.accepted=false;remove(p.getUniqueId());store.save();p.sendMessage(color(getConfig().getString("messages.paused")));}return true;}if(sub.equals("status")){p.sendMessage(color(x.accepted?getConfig().getString("messages.status-active"):getConfig().getString("messages.status-paused")));return true;}if(sub.equals("reload")&&p.hasPermission("verity.admin")){reloadConfig();p.sendMessage(ChatColor.GREEN+"Verity config reloaded.");return true;}if(!x.accepted){p.sendMessage(color(getConfig().getString("messages.not-accepted")));return true;}String m=String.join(" ",a);if(ignored(m)){reply(p,"The sphere does not keep that kind of secret.");return true;}groq.ask(p,x,m);return true;}
 private void tick(){if(!getConfig().getBoolean("events.enabled",true))return;long now=System.currentTimeMillis();for(Player p:Bukkit.getOnlinePlayers()){PlayerProfile x=store.get(p.getUniqueId());if(!x.accepted)continue;if(x.nextEventAt==0)schedule(x);if(now>=x.nextEventAt){event(p,x);schedule(x);}}}
 private void event(Player p,PlayerProfile x){if(getConfig().getBoolean("events.only-at-night-or-underground",false)&&p.getWorld().getTime()<13000&&p.getLocation().getBlockY()>55)return;x.encounters++;x.fear=Math.min(100,x.fear+1+random.nextInt(3));Location q=p.getLocation().clone().add((random.nextBoolean()?1:-1)*(5+random.nextInt(6)),1.5,(random.nextBoolean()?1:-1)*(5+random.nextInt(6)));spawn(p,q);p.playSound(p.getLocation(),Sound.AMBIENT_CAVE,.8f,.55f+random.nextFloat()*.35f);p.spawnParticle(Particle.REDSTONE,q,22,.7,.7,.7,new Particle.DustOptions(Color.fromRGB(150,0,0),1.1f));if(random.nextBoolean())reply(p,fallback(x));store.save();}
 private void spawn(Player p,Location l){remove(p.getUniqueId());ArmorStand a=l.getWorld().spawn(l,ArmorStand.class);a.setVisible(false);a.setGravity(false);a.setInvulnerable(true);a.setMarker(true);a.setSmall(true);a.setHelmet(new ItemStack(Material.CARVED_PUMPKIN));active.put(p.getUniqueId(),a);Bukkit.getScheduler().runTaskLater(this,()->remove(p.getUniqueId()),getConfig().getLong("events.max-active-seconds",18)*20L);}
 private void remove(UUID id){ArmorStand a=active.remove(id);if(a!=null&&!a.isDead())a.remove();} private void schedule(PlayerProfile p){int min=getConfig().getInt("events.min-delay-seconds",120),max=getConfig().getInt("events.max-delay-seconds",360);p.nextEventAt=System.currentTimeMillis()+(min+random.nextInt(Math.max(1,max-min+1)))*1000L;} public void remember(PlayerProfile p,String line){p.history.add(line);while(p.history.size()>getConfig().getInt("ai.max-history-messages",8))p.history.remove(0);} public void reply(Player p,String text){p.sendMessage(color(getConfig().getString("messages.prefix")+text));} public String fallback(PlayerProfile p){String[] z={"I saw the torch go out.","The cave remembers your footsteps.","Do not look behind the trees.","You invited me in.","The smile is closer than it was."};return z[random.nextInt(z.length)];}private boolean ignored(String m){String a=m.toLowerCase(Locale.ROOT);for(String q:getConfig().getStringList("privacy.ignored-words"))if(a.contains(q.toLowerCase(Locale.ROOT)))return true;return false;}private String color(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);}
}